version: '3'
services:
  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/images:/usr/share/nginx/images:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/usr/local/openresty/nginx/logs

volumes:
  nginx_cache:
  nginx_logs:
