services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./web/images:/usr/share/nginx/html/images:ro
      - ./web/conf.d:/etc/nginx/conf.d:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - network1

  test:
    build: 
      context: ./tests
    volumes:
      - ./tests/scripts:/scripts
    networks:
      - network1

networks:
  network1:
